# Documentation for ACL policy: https://aka.ms/gim/docs/policy/acl

name: Access control list
description: List of teams and their permission levels
resource: repository
where:
configuration:
  manageAccess:
  - member: duschroe
    role: Maintain
  - team: TM-CCPurchase-RW-d081
    role: Maintain
  - team: RAM_f771d797-6e18-47f0-a432-d4e9dd3a8d2f
    role: Maintain
  - team: RAM_1e7d4b6e-f627-4b30-8b87-6b69349e94e8
    role: Maintain